### ISSUE TITLE
Broken links in /_pages/datamodels.md

### ISSUE THREAD

**Issue by jipegit** [MISP/misp-website#7]
Several broken links in /master/_pages/datamodels.md:

- https://github.com/MISP/misp-taxonomies/tree/master/open-threat

- https://github.com/MISP/misp-taxonomies/tree/master/pap

- https://github.com/MISP/misp-taxonomies/tree/master/eu-critical-sectors

- https://github.com/MISP/misp-taxonomies/tree/master/europol-events

**Comment by adulau** [comment]
Thank you for reporting this. We updated the list and it's now automatically generated for the MANIFEST of taxonomies.
